### ISSUE TITLE
publish to NPM

### ISSUE THREAD

**Issue by kellyrmilligan** [patik/within-viewport#14]
would love to see this on npm as well.

**Comment by kellyrmilligan** [comment]
https://github.com/umdjs/umd  would also be great to add umd wrapper for browserify/webpack.

**Comment by patik** [comment]
How about this pattern? https://github.com/umdjs/umd/blob/master/amdWeb.js

**Comment by kellyrmilligan** [comment]
Looks good

**Comment by patik** [comment]
All set:

`npm install withinviewport --save-dev`

Reopen if you find any issues.
