### ISSUE TITLE
Always returns false

### ISSUE THREAD

**Issue by danparker92** [patik/within-viewport#16]
Hey, I'm not sure if I am doing something wrong or not but it seems to be returning false on every element pass through.

Perhaps this will help...
![screen shot 2015-04-26 at 13 06 57](https://cloud.githubusercontent.com/assets/1528599/7337119/54232328-ec15-11e4-8130-3eb772b87803.png)

**Comment by patik** [comment]
Can you try `withinviewport(document.getElementById('hello'))` ?

If that doesn't work, can you post the code somewhere (preferably a reduced test on Codepen, JSBin, etc) so I can try and debug it?

**Comment by deliver2manish** [comment]
I used this plugin and I also face same problem.
console.log(withinviewport(document.getElementsByClassName("quest-grid-image")[i])) always returns false even if the element is visible.

**Comment by patik** [comment]
I can't reproduce the bug in my own demos so I wonder if some other CSS in your page is affecting it. Can you link to the page or put a quick demo in Codepen/JSBin? Are there any iframes involved?

**Comment by deliver2manish** [comment]
I use it for this website: http://www.seenit.in. I included the ('js/jquery.withinviewport.js', 'js/withinviewport.js') files and used it as shown below:

    $(window).bind("scroll", function() {
        var i;
        for(i=0;i<12;i++){
            console.log(withinviewport(document.getElementsByClassName("quest-grid-image")[i]));
        }
    });

It always prints false on the console log, even if the element is fully visible on the screen.

**Comment by patik** [comment]
This is now fixed with [v1.0.0](https://github.com/patik/within-viewport/releases/tag/1.0.0). Thanks for including the example code. I believe the issue was that the `<div>` you were targeting was inside an `<a>` (i.e. an inline element, rather than a block) and that tripped up the part of my code that calculates the target element's position. I'm using a faster and more robust method now.

**Comment by deliver2manish** [comment]
Thanks. It fixes the bug for me.



On Mon, Aug 3, 2015 at 4:19 AM, Craig Patik <notifications@github.com>
wrote:

> This is now fixed with v1.0.0
> <https://github.com/patik/within-viewport/releases/tag/1.0.0>. Thanks for
> including the example code. I believe the issue was that the <div> you
> were targeting was inside an <a> (i.e. an inline element, rather than a
> block) and that tripped up the part of my code that calculates the target
> element's position. I'm using a faster and more robust method now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/patik/within-viewport/issues/16#issuecomment-127079568>
> .
>



-- 
"Stay Hungry, Stay Foolish"
