### ISSUE TITLE
jQuery plugin doesn't work

### ISSUE THREAD

**Issue by mr-moon** [patik/within-viewport#18]
```
$.extend($.expr[':'], {
    'within-viewport': function (element) {
        return withinviewport(element, 'all'); // <-- withinviewport is undefined VM18007 jquery.withinviewport.js:37
    }
});
```

**Comment by patik** [comment]
Have you updated the [main file](https://github.com/patik/within-viewport/blob/master/withinviewport.js) to v1.0.0? The last update changed the case of the name (it's now a lowercase `v`) so it's possible your copy is still defining `withinViewport` with a capital `V`.

If you open the [demo page](http://patik.github.io/within-viewport/), which includes the jQuery plugin, you can call something like `$('div:within-viewport')` and it works as expected.

**Comment by patik** [comment]
If you are still having an issue, please point to a reduced test case that I can debug.
